<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>cryptokey</AssemblyName>
    <TargetFramework>net9.0</TargetFramework>
    <RuntimeIdentifiers>osx-arm64;osx-x64</RuntimeIdentifiers>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="CryptoKey.Tests" />
    <ProjectReference Include="..\CryptoKey.Core\CryptoKey.Core.csproj" />
    <ProjectReference Include="..\CryptoKey.Ui\CryptoKey.Ui.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Assets\tray.png" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.3.22" />
    <PackageReference Include="Avalonia.Desktop" Version="11.3.22" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="11.3.22" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.3.22" />
  </ItemGroup>

</Project>
