<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>cryptokey</AssemblyName>
    <TargetFramework>net9.0</TargetFramework>
    <RuntimeIdentifiers>osx-arm64;osx-x64</RuntimeIdentifiers>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="CryptoKey.Tests" />
    <ProjectReference Include="..\CryptoKey.Core\CryptoKey.Core.csproj" />
  </ItemGroup>

</Project>
