"""Regenerates src/CryptoKey.Ui/Design/IconData.cs from Lucide (ISC license).

Each Lucide icon is a 24x24 stroked SVG built from path/rect/circle/line/
polyline/polygon/ellipse elements. Avalonia strokes a single geometry, so
every element is flattened into path markup here once, at dev time — the
app ships plain strings, no SVG parser.

    python tools/gen_icons.py
"""
import re
import urllib.request
import xml.etree.ElementTree as ET
from pathlib import Path

# Lucide name -> C# constant name.
ICONS = {
    "house": "Home",
    "key-round": "Key",
    "shield-check": "Shield",
    "bell-ring": "Bell",
    "activity": "Activity",
    "settings": "Settings",
    "info": "Info",
    "vault": "Vault",
    "usb": "Usb",
    "lock": "Lock",
    "lock-open": "Unlock",
    "pause": "Pause",
    "play": "Play",
    "timer": "Timer",
    "refresh-cw": "Refresh",
    "folder-open": "Folder",
    "camera": "Camera",
    "eye": "Eye",
    "eye-off": "EyeOff",
    "triangle-alert": "Warning",
    "check": "Check",
    "x": "Close",
    "minus": "Minimize",
    "square": "Maximize",
    "copy": "Restore",
    "log-out": "Quit",
    "download": "Download",
    "chevron-right": "ChevronRight",
    "chevron-down": "ChevronDown",
    "chevron-left": "ChevronLeft",
    "cpu": "Cpu",
    "trash": "Trash",
    "rotate-ccw": "Undo",
    "webhook": "Webhook",
    "monitor": "Monitor",
    "external-link": "External",
    "circle-check": "CircleCheck",
    "circle-alert": "CircleAlert",
    "fingerprint-pattern": "Fingerprint",
    "search": "Search",
    "panel-left": "PanelLeft",
    "zap": "Zap",
    "scan-line": "Scan",
    "plug": "Plug",
    "power": "Power",
    "hard-drive": "Drive",
    "terminal": "Terminal",
    "sparkles": "Sparkles",
    "volume-2": "Sound",
    "user-cog": "Admin",
    "link": "Link",
    "file-key": "FileKey",
    "wrench": "Wrench",
    "arrow-right": "ArrowRight",
    "arrow-left": "ArrowLeft",
    "printer": "Printer",
    "pen-line": "Pen",
}

SRC = "https://raw.githubusercontent.com/lucide-icons/lucide/main/icons/{}.svg"
OUT = Path(__file__).resolve().parent.parent / "src" / "CryptoKey.Ui" / "Design" / "IconData.cs"


def f(v):
    x = float(v)
    return str(int(x)) if x == int(x) else repr(round(x, 4))


def rect(a):
    x, y = float(a.get("x", 0)), float(a.get("y", 0))
    w, h = float(a["width"]), float(a["height"])
    rx = float(a.get("rx", a.get("ry", 0)))
    ry = float(a.get("ry", rx))
    if rx == 0:
        return f"M{f(x)},{f(y)} H{f(x+w)} V{f(y+h)} H{f(x)} Z"
    return (f"M{f(x+rx)},{f(y)} H{f(x+w-rx)} A{f(rx)},{f(ry)} 0 0 1 {f(x+w)},{f(y+ry)} "
            f"V{f(y+h-ry)} A{f(rx)},{f(ry)} 0 0 1 {f(x+w-rx)},{f(y+h)} "
            f"H{f(x+rx)} A{f(rx)},{f(ry)} 0 0 1 {f(x)},{f(y+h-ry)} "
            f"V{f(y+ry)} A{f(rx)},{f(ry)} 0 0 1 {f(x+rx)},{f(y)} Z")


def ellipse(cx, cy, rx, ry):
    return (f"M{f(cx-rx)},{f(cy)} A{f(rx)},{f(ry)} 0 1 0 {f(cx+rx)},{f(cy)} "
            f"A{f(rx)},{f(ry)} 0 1 0 {f(cx-rx)},{f(cy)} Z")


def points(s, close):
    nums = [float(n) for n in re.split(r"[\s,]+", s.strip()) if n]
    pts = list(zip(nums[0::2], nums[1::2]))
    d = "M" + " L".join(f"{f(x)},{f(y)}" for x, y in pts)
    return d + (" Z" if close else "")


NUM = r"-?(?:\d+\.?\d*|\.\d+)(?:e-?\d+)?"


def absolutize(d):
    """A path's leading 'm' is absolute in isolation but relative once
    concatenated after another subpath — rewrite it as 'M', keeping any
    implicit follow-on pairs as relative linetos ('l')."""
    d = d.strip()
    m = re.match(rf"m\s*({NUM})[\s,]*({NUM})(.*)", d, re.S)
    if not m:
        return d
    rest = m.group(3).lstrip(" ,")
    if rest and re.match(r"[-.\d]", rest):
        rest = "l" + rest
    return f"M{m.group(1)} {m.group(2)} {rest}".strip()


def convert(svg):
    root = ET.fromstring(svg)
    parts = []
    for el in root:
        tag = el.tag.split("}")[-1]
        a = el.attrib
        if tag == "path":
            parts.append(absolutize(a["d"]))
        elif tag == "rect":
            parts.append(rect(a))
        elif tag == "circle":
            r = float(a["r"])
            parts.append(ellipse(float(a["cx"]), float(a["cy"]), r, r))
        elif tag == "ellipse":
            parts.append(ellipse(float(a["cx"]), float(a["cy"]), float(a["rx"]), float(a["ry"])))
        elif tag == "line":
            parts.append(f"M{f(a['x1'])},{f(a['y1'])} L{f(a['x2'])},{f(a['y2'])}")
        elif tag == "polyline":
            parts.append(points(a["points"], False))
        elif tag == "polygon":
            parts.append(points(a["points"], True))
        else:
            raise ValueError(f"unhandled element {tag}")
    return " ".join(parts)


def main():
    lines = [
        "// <auto-generated> by tools/gen_icons.py from Lucide (https://lucide.dev, ISC license).",
        "// Do not edit by hand — rerun the generator.",
        "namespace CryptoKey.Ui;",
        "",
        "/// <summary>24x24 stroked Lucide icon outlines as Avalonia path markup.</summary>",
        "internal static class IconData",
        "{",
    ]
    for name, const in ICONS.items():
        try:
            with urllib.request.urlopen(SRC.format(name)) as r:
                data = convert(r.read().decode())
        except Exception as e:
            raise SystemExit(f"icon '{name}': {e}")
        lines.append(f"    public const string {const} = \"{data}\";")
    lines.append("}")
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {OUT} ({len(ICONS)} icons)")


if __name__ == "__main__":
    main()
