<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>cryptokey</AssemblyName>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationHighDpiMode>PerMonitorV2</ApplicationHighDpiMode>
    <NoWarn>$(NoWarn);WFO5001;WFO1000</NoWarn>
    <ApplicationIcon>app.ico</ApplicationIcon>
    <Version>0.9.0</Version>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="CryptoKey.Tests" />
    <PackageReference Include="FlashCap" Version="1.12.0" />
    <PackageReference Include="System.IO.Pipes.AccessControl" Version="5.0.0" />
    <PackageReference Include="System.Management" Version="10.0.12" />
    <PackageReference Include="System.Security.Cryptography.ProtectedData" Version="10.0.12" />
  </ItemGroup>

</Project>